const mongoose = require('mongoose');

const propertySchema = new mongoose.Schema({
  labels: [String],
  categories: [String],
  plan: { type: String, enum: ['Plan A', 'Plan B'], required: true }, // Add this line
  imageUrl: String,
  Plogo: String,
  by:String,
  developer: { type: mongoose.Schema.Types.ObjectId, ref: 'Developer' },
  name: String,
  location: String,
  price: String,
  status: String,
  configuration: String,
  locationAbout:String,
  possession: String,
  units: Number,
  land: String,
  residence: String,  // Fixed the typo from 'recidence' to 'residence'
  builtup: String,
  blocks: String,
  floor: String,
  noofunits: Number,
  reraCode:String,
  rera: [String],  // Updated this line to be an array of strings
  point1: String,
  point2: String,
  point3: String,
  point4: String,
  point5: String,
  about: String,
  pdf1: String,
  payment: String,
  unitytype: String,
  size: String,
  range: String,
  booking: String,
  token: String,
  pdf2: String,
  floorImg1: String,
  floorImg2: String,
  floorImg3: String,
  floorImg4: String,
  floorImg5: String,
  floorImg6: String,
  floorImg7: String,
  floorImg8: String,
  floorImg9: String,
  floorImg10: String,
  logoText1: String,
  logoText2: String,
  logoText3: String,
  logoText4: String,
  logoText5: String,
  logoText6: String,
  logoText7: String,
  logoText8: String,
  logoText9: String,
  logoText10: String,
  icon: [String],
  locationImage: String
});

module.exports = mongoose.model('Property', propertySchema);
